services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5001"
    environment:
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5001"
      DB_HOST: "host.docker.internal"
      DB_USER: "root"
      DB_PASSWORD: "123456789"
      DB_NAME: "collaborators_db"
      MINIMUM_SIMILARITY_THRESHOLD: "0.49"